In [1]:
from tensorflow.keras.datasets import mnist

In [2]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [3]:
train_images.shape

(60000, 28, 28)

In [18]:
 train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [5]:
test_images.shape

(10000, 28, 28)

In [6]:
len(test_labels) 


10000

In [7]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

`The network architecture`

In [8]:
from tensorflow import keras
from tensorflow.keras import layers

In [9]:
model = keras.Sequential([
 layers.Dense(512, activation="relu"),
 layers.Dense(10, activation="softmax")
])

`The compilation step`

In [10]:
model.compile(optimizer="rmsprop",
 loss="sparse_categorical_crossentropy",
 metrics=["accuracy"])

`Preparing the image data`

In [11]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255

` “Fitting” the model`

In [12]:
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 7s 13ms/step - loss: 0.2645 - accuracy: 0.9229
Epoch 2/5
469/469 [==============================] - 5s 10ms/step - loss: 0.1087 - accuracy: 0.9678
Epoch 3/5
469/469 [==============================] - 6s 13ms/step - loss: 0.0704 - accuracy: 0.9791
Epoch 4/5
469/469 [==============================] - 5s 10ms/step - loss: 0.0513 - accuracy: 0.9847
Epoch 5/5
469/469 [==============================] - 5s 10ms/step - loss: 0.0389 - accuracy: 0.9884


`Using the model to make predictions`

In [13]:
test_digits = test_images[0:10]
predictions = model.predict(test_digits)
predictions[0]

1/1 [==============================] - 0s 85ms/step


array([6.7921796e-08, 1.5395416e-08, 2.5838237e-05, 1.6255623e-04,
       2.5639822e-11, 1.4599257e-07, 8.2909737e-13, 9.9980998e-01,
       2.0151913e-07, 1.2357535e-06], dtype=float32)

In [14]:
predictions[0].argmax() 

7

In [15]:
predictions[0][7]

0.99981

In [16]:
test_labels[0]

7

`Evaluating the model on new data`

In [17]:
 test_loss, test_acc = model.evaluate(test_images, test_labels)
 print(f"test_acc: {test_acc}")

313/313 [==============================] - 2s 5ms/step - loss: 0.0598 - accuracy: 0.9825
test_acc: 0.9825000166893005
